### ISSUE TITLE
Support nested expression

### ISSUE THREAD

**Issue by tanbowensg** [webzard-io/sunmao-ui#113]
When using module as template in list, we may write something like this `{{ moduleName{{$listItem.id}}.stateValue }}`. This expression cannot be parsed correctly now.

**Comment by Yuyz0112** [comment]
How about `moduleName[$listItem.id].stateValue`, where `$listItem` is a runtime object we injected into the eval scope during looping a list.

**Comment by tanbowensg** [comment]
@Yuyz0112 But the component Id is `moduleName{{$listItem.id}}`. There is not `moduleName[$listItem.id]`.
