### ISSUE TITLE
fix dragging between two draggable item

### ISSUE THREAD

**Issue by Sczlog** [webzard-io/sunmao-ui#195]
drag between two draggable element will not change drag id.
![sunmaodrag](https://user-images.githubusercontent.com/29588646/148003439-5f0337ce-c57d-40e8-a05e-dbb5c29f7df6.gif)

**Comment by Sczlog** [comment]
root cause:
dragenter occur after dragleave for sibling element

**Comment by tanbowensg** [comment]
After the refactoring of editor mask, this bug does not exist any more.
