### ISSUE TITLE
Improve folder/file naming

### ISSUE THREAD

**Issue by Yuyz0112** [webzard-io/sunmao-ui#197]
Currently, there are several different naming strategies in sunmao-ui's code repo, like:

- src/AppModel/AppModel.ts
- src/AppModel/utils.ts
- src/components/Editor.tsx
- operations/branch/createComponentBranchOperation.ts

BTW, the hierarchy of folders is also deep and complex.

## Expectations

Have a coding style description doc about naming, which keeps the code style consistent and easy to search, for both core team members and community contributors.

**Comment by tanbowensg** [comment]
Good.
