### ISSUE TITLE
Support properties classification

### ISSUE THREAD

**Issue by MrWindlike** [webzard-io/sunmao-ui#211]
### What problem does this feature solve?
Now all the properties is all put together under the `Properties` tab. It is hard to find the property which user want to set when the component become more and more complex. Thus, the inspect form of editor should support properties classification by their different function.

![image](https://user-images.githubusercontent.com/25414733/149883954-2c7f31fc-1d84-4ba6-8f3e-6967561cd13e.png)

### What does the feature look like?
![image](https://user-images.githubusercontent.com/25414733/149884082-2dda6709-c31b-44d9-9736-0796e54540c0.png)

**Comment by Yuyz0112** [comment]
Short proposal: how about using a field in props' meta area, like `category`?

For example:
```ts
const name = Type.String({
  category: "basic"
});

const format = Type.String({
  category: "advance"
});
```
