### ISSUE TITLE
Improve state viewer

### ISSUE THREAD

**Issue by tanbowensg** [webzard-io/sunmao-ui#246]
**What problem does this feature solve?**
* state updates in realtime
* can show state of current selected component instead of all components.

**Comment by Yuyz0112** [comment]
A PR for this issue: https://github.com/webzard-io/sunmao-ui/pull/244

> can show state of current selected component instead of all components.

Not sure this is a goal of the state viewer. I think a use case of the state viewer is the user wants to write an expression for a component, which may use the state from other components in the global store. So only showing the current component's state does not help this use case.

The new state viewer looks like this:

![image](https://user-images.githubusercontent.com/13651389/151686029-4f7d9262-4d56-4a04-a1e1-264ad93464ce.png)

The new UI collapse by default, and use a more compact way to show the fields. Does this helps solve the initial problem?

**Comment by tanbowensg** [comment]
I think what I really want is a way to quickly find a component state. The state tree is unorderer. When it comes to many components, finding a particular one maybe difficult.

**Comment by Yuyz0112** [comment]
Got it. Maybe a search input to filter the keys and order the keys by alphabet will help.
