### ISSUE TITLE
Improve Form

### ISSUE THREAD

**Issue by tanbowensg** [webzard-io/sunmao-ui#252]
**What problem does this feature solve?**
Before solving this issue, we should design the new spec of the property. #251 
related issue: #211 

The new Form should improve these points:
- [x] Better array and object editor. Array editor should support different types of item.
- [x] The special forms like `FetchTraitForm`, `EventHanlderForm` should use the same form widgets as other normal forms.
- [x] The Form widgets can collapse.
- [x] The Form widgets can be grouped and ordered.
- [x] The Form widgets can display title, description...
- [ ] #250 Can auto-scroll to an input.
- [ ] Conditional Form. Mainly used in table column form.
- [x] Prevent recursively render form fields for some property, like `data` in table. Set max height for expression editor.
- [x] Press tab to switch input.
- [ ] Value type may change after switch to or from `ExpressionEditor`.

**What does the proposed API look like?**

**Comment by Yuyz0112** [comment]
> Better array and object editor. Array editor should support different types of elements(string, object, any...)

What's the expectation of this improvement?

Currently, the `ArrayField` consists of some array-related operation UI and [bypass nested schema to a `SchemaField`](https://github.com/webzard-io/sunmao-ui/blob/main/packages/editor/src/components/ComponentForm/JsonSchemaForm/ArrayField.tsx#L75), which will recursively render form fields by the schema.

**Comment by tanbowensg** [comment]
Can we support conditional form. For example in table column form, a column has many `types` and each `type` has its own property. Can we show different fields according to the value of `type`?

**Comment by MrWindlike** [comment]
> The special forms like FetchTraitForm, EventHanlderForm should use the same form widgets as other normal forms.

@tanbowensg  Can the [PR](https://github.com/webzard-io/sunmao-ui/pull/299)'s changes meet this point? If yes, I mark it to complete.

**Comment by tanbowensg** [comment]
The remaining issues has other individual issues, so I close this issue.
