### ISSUE TITLE
Proposal: Expressive spec

### ISSUE THREAD

**Issue by Yuyz0112** [webzard-io/sunmao-ui#261]
**What problem does this feature solve?**

We already have some issues with improving the spec:

- https://github.com/webzard-io/sunmao-ui/issues/251
- https://github.com/webzard-io/sunmao-ui/issues/211

With a more expressive spec, we can tell more about a component/trait/application to the user or the editor.

**What does the proposed API look like?**

### Metadata

To keep the metadata area clean and maintainable, we will only add one field `annotations` to its schema.

The annotations will have a type of `JSONSchemaObject`.

```json
{
  "name": "Table",
  "description": "A Table component",
  "annotations": {
    "maintainer": "developer@sunmao-ui",
    "git": {
      "revision": "v1.0-hash",
      "repo_url": "https://github.com/webzard-io/sunmao-ui"
    },
    "have_a_pricing_plan": true
  }
}
```

#### properties

Since we are using JSON schema to describe properties, we will follow JSON schema to describe more information of a component.

I'm going to propose three ways to organize the information.

*1: Without namespace*

```json
{
  "width": {
    "type": "number",
    "title": "Width",
    "description": "width of the component in pixel",
    "widget": "WidthSlider"
  }
}
```

*2: With nested namespace*

```json
{
  "width": {
    "type": "number",
    "editor": {
      "title": "Width",
      "description": "width of the component in pixel",
      "widget": "WidthSlider"
    }
  }
}
```

*3: With plain namespace*

```json
{
  "width": {
    "type": "number",
    "editor:title": "Width",
    "editor:description": "width of the component in pixel",
    "editor:widget": "WidthSlider"
  }
}
```

To tell the editor how to display property in the form, we define the following fields:

- title: will display as the label of the form control
- description: will display as the help text of the form control
- widget: will determine which form control will be used
- category: properties will be grouped by category in the form, properties without a category will fall back to the `basic` category.

### Metadata

Same as the Component metadata.

#### properties

Same as the ComponentSpec properties.

### Metadata

Same as the Component metadata.

To tell the runtime how to render the head of the HTML, we define the following rules of the annotation fields:

- title: will render `<title>` in the `<head>`
- meta: will render `<meta>` in the `<head>`
- link: will render `<link>` in the `<head>`

An example of application's annotation:

```json
{
  "name": "Blog",
  "description": "My Blog Website",
  "annotations": {
    "title": "sunmao-ui developer blog",
    "meta": [
      {
        "name": "viewport",
        "content": "width=device-width"
      },
      {
        "name": "description",
        "content": "the blog website to record our thought on the sunmao-ui project"
      }
    ],
    "link": [
      {
        "rel": "alternate icon",
        "type": "image/png",
        "href": "https://github.githubassets.com/favicons/favicon.png"
      }
    ]
  }
}

```

**Comment by Yuyz0112** [comment]
Off-topic: A preferred way to display property categories in the editor

![image](https://user-images.githubusercontent.com/13651389/152781409-adf7e0cb-c0f7-4961-913b-8f36c26a8276.png)

**Comment by tanbowensg** [comment]
> ### ComponentMetadata
> #### May add a field to support classification for components?
> It's important to classify the components.
> 
> ### ComponentSpec
> #### Should support custom form items by `widget` property?
> In some situations, the component lib developers maybe can't find a suitable form item for the property. If we can support custom form items, it may help a lot for the component lib developers to build the component inspect form.
> 
> The spec of property may look like this:
> 
> ```js
> {
>   "color": {
>     "type": "string",
>     "title": "Color",
>     "description": "color of the text",
>     "widget": (formkit)=> (
>       <ColorPicker value={formkit.values.color} onChange={formkit.handleChange}>
>     )
>   }
> }
> ```
> 
> #### Should support condition render for form item?
> Some properties are may related to others. For example, the chart component would enable the `barWidth` property when the value of `type` is `bar`.
> 
> Maybe could add a `condition` field to the property spec, and the type of its value could be `(value: Static<PropertySchema>)=> boolean`.
> 
> ```js
> {
>   "barWidth": {
>     "type": "string",
>     "title": "Bar Width",
>     "description": "the width of the bar",
>     "condition": (values)=> (
>       values.type === 'bar'
>     )
>   }
> }
> ```
> 
> #### Maybe the `category` as the parent of the properties spec is better?
> I think the put the properties spec under the `category` is more clear to read in code. And it can be easier to extend the category's properties in the future.
> 
> ```js
> {
>   "basic": {
>     "kind": "category",
>     "title“?: "Basic",
>     "description"?: "",
>     "condition"?: (values)=> true,
>     "properties": {
>       "width": {
>         "type": "number",
>         "title": "Width",
>         "description": "width of the component in pixel",
>         "widget": "WidthSlider"
>       }
>     }
>   }
> }
> ```

But spec is json. Functions are not allowed in json and cannot be saved persistently.

**Comment by tanbowensg** [comment]
I preffer 3: With plain namespace. It can avoid conflict when a property is an object and has a key called `title` or `description`.

```
{
  "width": {
    "type": "number",
    "editor:title": "Width",
    "editor:description": "width of the component in pixel",
    "editor:widget": "WidthSlider"
  }
}
```

**Comment by Yuyz0112** [comment]
@MrWindlike same as @tanbowensg mentioned, the spec is a static, serializable, language-agnostic data structure that will not support features like function.

Back to the questions.

> Should support custom form items by widget property?

Yes, we can. We will support registering custom form UI to the editor with a widget name, and the spec will use that name to specify the form UI of a property.

> Should support condition render for form item?

Looks a bit complex to introduce in the current stage. Other possible solutions:

1. Divide one general chart component into multiple specific charts components, like a bar chart, a line chart, etc.
2. Use union schema.

> Maybe the category as the parent of the properties spec is better?

Could you explain this a little more?

**Comment by Yuyz0112** [comment]
An update:

How about fallback entities without `category` to `advance` instead of `basic`? This pushes developers to define categories explicitly.

**Comment by tanbowensg** [comment]
> An update:
> 
> How about fallback entities without `category` to `advance` instead of `basic`? This pushes developers to define categories explicitly.

And push `advance` category to the bottom of form

**Comment by tanbowensg** [comment]
We may add a field `default` to properties spec to set default value.

**Comment by Yuyz0112** [comment]
> We may add a field default to properties spec to set default value.

@tanbowensg Is this a default value or an example value? For default, I think somebody may think it means when we do not pass any value to the component, it will use the default value.

**Comment by MrWindlike** [comment]
> Could you explain this a little more?

If the `category` is defined under the properties' spec, it would allow the component lib developer to write it optionally. It may make some mistakes: 
```js
{
  "properties": {
    "width": {
      "type": "number",
      "title": "Width",
      "description": "width of the component in pixel",
      "widget": "WidthSlider",
      "category": "basic"
    },
   "background": {
      "type": "string",
      "title": "Background",
      "category": "color"  // May the properties under the same category are not defined together
    },
    "height": {
      "type": "number",
      "title": "Height",
      "category": "basic"  // Every properties should define category repeatedly
    },
    "type": {
      "type": "string",
      "title": "Type",
      "category": "Basic"  // May write typo
    },
  }
}
```

In addition, it is also hard to extend some properties for categories in the future. For example, we may want to add the description for some categories.

If we defined the categories as the properties spec's parents, it wouldn't have these problems. But the disadvantage is that this may need to change the struct of the current component spec a lot.

**Comment by Yuyz0112** [comment]
@MrWindlike 

I see, the main point here is we are using [JSON schema](https://json-schema.org/) to describe the properties, and using some toolchains from the JSON schema ecosystem like validation.

Does the schema you proposed a valid JSON schema?
