### ISSUE TITLE
A type of DataSource: Transformer

### ISSUE THREAD

**Issue by tanbowensg** [webzard-io/sunmao-ui#308]
Transformer is something like `pipe` or `computed`. In `runtime` implementation, it is a very typical trait——get props and return result.
# Use Cased
1. Data from `Fetch` cannot be used directly. We can use Transformer to format it.
2. `Form` component has a lot of custom form widgets. We can use Transformer to combine these value of widgets to a whole form data.

**Comment by Yuyz0112** [comment]
Is this a trait or a trait property?

**Comment by tanbowensg** [comment]
It is a trait.
The transformer need a `lazy` property. Because transformer sometimes maybe expensive and should triggered by event.
