### ISSUE TITLE
Provide more custom widgets

### ISSUE THREAD

**Issue by xzdry** [webzard-io/sunmao-ui#363]
For example, the widget used to describe margin and padding like:

<img width="219" alt="image" src="https://user-images.githubusercontent.com/96771399/161005010-1589ed9f-99c9-460e-950c-d475273caaa4.png">

for describing aligned widgets like:
<img width="140" alt="image" src="https://user-images.githubusercontent.com/96771399/161005914-56bf1ff9-9fdd-4a75-a303-a8a65b5a8299.png">
and more user-friendly custom widgets

**Comment by Yuyz0112** [comment]
![image](https://user-images.githubusercontent.com/13651389/161006988-50e5ea62-7a5b-48ef-b7f7-f2e88ca45b3f.png)

refernce: webflow's editor

**Comment by tanbowensg** [comment]
<img width="370" alt="截屏2022-05-27 下午4 25 01" src="https://user-images.githubusercontent.com/12260952/170661273-1195f11a-12a5-4d99-83e2-ebde9a40f367.png">

**Comment by tanbowensg** [comment]
margin: ruoyu
color: yangfeng
