### ISSUE TITLE
编辑模式下，是否能禁用掉按钮的事件或者跳转

### ISSUE THREAD

**Issue by wuchangming** [webzard-io/sunmao-ui#647]
**What problem does this feature solve?**
比如这个按钮在编辑状态下也是能跳转的，感觉会影响编辑状态下的开发效率。
![image](https://user-images.githubusercontent.com/5039340/203944969-99dce870-0eff-494c-9ec3-ace1f21513a2.png)

**What does the proposed API look like?**

**Comment by tanbowensg** [comment]
确实有时候这会影响开发，不过目前也不能随便禁用掉组件的事件。因为从框架层面来说，很难去阻止组件内部去进行一些行为；从组件实现来说，也很难预测定义的事件会被用来触发什么事情。比如这个按钮的开发者就没法预料到它有可能被用来跳转页面。

如果实在想要解决，也有办法。目前框架会给Component传一个`isInEditor`的参数用来判断目前是否在编辑器中，进而做一些特定处理。但是目前在框架层面，不会对编辑器中的组件行为做出限制。

**Comment by wuchangming** [comment]
也是，这也是一种方案，实现组件的时候自行去处理。
