### ISSUE TITLE
体验官网 demo 没有找到如何来配置动效

### ISSUE THREAD

**Issue by fedono** [webzard-io/sunmao-ui#674]
跟着官网的 demo 配置，没看到这个是咋配置出来的

如果我要修改左侧的代码内容和右侧的图片，要咋改呢，这个是引用啥组件么？
这个是咋做到往下滑动，但是这个组件没有往上滚动呢？而是在切换动画的？

![image](https://user-images.githubusercontent.com/12681297/212228083-c96ea162-3d53-4157-862e-f29ff22455b1.png)

**Comment by tanbowensg** [comment]
这个动画是通过我们封装了一个 Sunmao 组件用 JS 来实现的，代码在这里：
https://github.com/webzard-io/sunmao-site/blob/main/src/sunmao/components/CodeSurf.tsx

背景图片是在 `day2CodeImage` 组件的style里面修改
![截屏2023-01-13 下午1 55 24](https://user-images.githubusercontent.com/12260952/212247917-56e53983-6a03-4ff3-b707-092b59663576.png)


左边的代码因为行数太多，所以我们是在 JS 中作为以来注入进去的，在这里：
https://github.com/webzard-io/sunmao-site/blob/main/src/sunmao/lib.ts#L25
