### ISSUE TITLE
内存泄漏了吧，用的sunmao cloud

### ISSUE THREAD

**Issue by sukbearai** [webzard-io/sunmao-ui#676]
**Version**  
    "@sunmao-ui/arco-lib": "^0.5.0",
    "@sunmao-ui/core": "^0.9.0",
    "@sunmao-ui/echarts-lib": "^0.2.0",
    "@sunmao-ui/runtime": "^0.9.0",

**Reproduction link** https://sunmao-ui.com/dev.html

**What is actually happening?** 

![控制台错误，浏览器卡死](https://user-images.githubusercontent.com/120086676/212252471-c8ec3239-26cb-4f6a-a08f-c5af5c2a4273.png)

表单验证的example可以换成arco版本嘛？

**Comment by tanbowensg** [comment]
我这边好像没有内存泄漏的情况。你还进行了什么额外操作吗？
<img width="1436" alt="截屏2023-01-13 下午4 14 31" src="https://user-images.githubusercontent.com/12260952/212271121-45c5f3e2-d419-463b-a2d6-54676ec9f4fc.png">


表单验证的example的话，这个应该就是arco版本的：
https://github.com/smartxworks/sunmao-ui/blob/develop/examples/form/formValidation.json

**Comment by sukbearai** [comment]
刷新浏览器可以了，我看examples form这个组件可以替换成arco的吗，这样可以统一表单验证吧，不用在额外引入chakra-ui

**Comment by sukbearai** [comment]
![微信图片_20230113172250](https://user-images.githubusercontent.com/120086676/212285009-ef8e20ee-777d-47b7-adbf-5c3c7f6a42bb.png)
我没理解这个module是怎么回事，我只想渲染组件，但是不能按预期实现，这个module是做什么的呢？

**Comment by tanbowensg** [comment]
> 刷新浏览器可以了，我看examples form这个组件可以替换成arco的吗，这样可以统一表单验证吧，不用在额外引入chakra-ui

可以的。实际上现在也不推荐用chakra-ui了。因为维护两个库工作量太大了，所以现在只专心维护arco库了。

> 我没理解这个module是怎么回事，我只想渲染组件，但是不能按预期实现，这个module是做什么的呢？

module 是个进阶功能，所以文档里还没写。module 可以理解为封装起来的一堆组件，可以在Sunmao级别切分和复用组件。如果没有module的话，传空数组就可以了。

**Comment by cyberbear181** [comment]
我尝试在nextjs中使用sunmao/runtime，目前这个错误不知是什么原因造成的，应该不是ssr的问题，因为我判断在浏览器环境下渲染sunmaoApp

**Comment by cyberbear181** [comment]
<img width="578" alt="image" src="https://user-images.githubusercontent.com/120086676/212321601-ff53cb0c-5ee7-41a5-a1b5-704b5f78b017.png">

**Comment by cyberbear181** [comment]
<img width="995" alt="image" src="https://user-images.githubusercontent.com/120086676/212322450-73781c50-a9b4-49e7-bf09-e3eb2179f109.png">

**Comment by cyberbear181** [comment]
<img width="841" alt="image" src="https://user-images.githubusercontent.com/120086676/212329114-b2bf188b-86ae-4798-b81f-7887a73c92a2.png">

**Comment by sukbearai** [comment]
https://github.com/cyberbear181/sunmao-arco-next.git 添加 sunmao-ui 到 next 项目,ssr渲染模式下会报错
