### ISSUE TITLE
FormControl组件添加field属性渲染时会丢失

### ISSUE THREAD

**Issue by sukbearai** [webzard-io/sunmao-ui#684]
1. 
<img width="665" alt="image" src="https://user-images.githubusercontent.com/120086676/213701578-7f130d2b-8d70-4a33-ab9b-68711402ec23.png">
2.
<img width="1419" alt="image" src="https://user-images.githubusercontent.com/120086676/213701775-03630b28-a0db-4d63-bb00-09b837248e86.png">
3.
 <img width="883" alt="image" src="https://user-images.githubusercontent.com/120086676/213701860-db769e4b-4a97-4db7-bab6-15eb99e0c9aa.png">

图3是官方给出的例子，渲染后会添加id属性。

4.
<img width="899" alt="image" src="https://user-images.githubusercontent.com/120086676/213703165-3419e0fe-ad0f-4424-9daa-09f6c4bd2d1a.png">

点击submit按钮后返回的是{},期望返回{name: undefined, age: undefined}包含所有formItem的field key的对象。

**Comment by sukbearai** [comment]
slotsElements.content在渲染的时候好像把field属性给移除了？导致form收集不到表单项的值

**Comment by xzdry** [comment]
arco的Form.Item只会对唯一子节点传递对应的props属性。并且需要自行在自定义组件内提交自己的值。而`slotsElements.content`是一个数组（因为一个slot插槽可以插入多个组件），这时候Form.Item会直接返回传入的children。
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/96771399/215406526-ebdc7328-e1e8-46a0-945b-da7ab114a035.png">
